FROM ubuntu:22.04

MAINTAINER Chun Shen <chunshen@wayne.edu>

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
    apt-get update && apt-get install -y --no-install-recommends \
        cmake \
        cmake-data \
        curl \
        g++ \
        gcc \
        gfortran \
        git \
        hdf5-tools \
        libfftw3-dev \
        libgsl-dev \
        libhdf5-dev \
        libeigen3-dev \
        libz-dev \
        make \
        pkg-config \
        python3 \
        python3-pip \
        time \
        vim \
        wget \
        build-essential \
        openmpi-bin \
        libopenmpi-dev \
        libboost-all-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install pre-reqs python packages
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install numpy h5py scipy PyYAML joblib mpmath freestream

ENV HOME /opt/

# download and compile the iEBE-MUSIC framework
RUN cd ${HOME} \
&& git clone https://github.com/genilssom/iEBE-MUSIC -b TRENToFreestream \
&& cd iEBE-MUSIC/codes \
&& ./get_code_packages.sh \
&& ./compile_code_packages.sh \
&& cd ../EOS_database \
&& bash download_EOSdatabase1D.sh \
&& bash download_QGPViscositydatabase1D.sh \
&& cd ../initialcondition_database \
&& bash download_smoothTATB.sh \
&& cd ../config/arXiv_2507.11394 \
&& bash download_posteriorChains.sh \
&& cd ../arXiv_2408.00537 \
&& bash download_posteriorChain.sh

ENV PYTHONIOENCODING utf-8

WORKDIR ${HOME}/iEBE-MUSIC

CMD /bin/bash
