
isobar_seeds:
   description: Configurations for making list of seeds for nucleon positions.
   
   number_nucleons: 
      description: Mass number A of the nuclei.
      value: 197
   
   number_configs:
      description: How many sets of nucleon positions to sample?
      value: 50000
         
   output_file:
      description: Path where to save list of seeds for nucleon positions.
      filename: nucleon-seeds_AuAu.hdf
      
   number_of_parallel_processes:
       description: Number of processes to compute in parallel. A value of -1 automatically selects the number of CPUs present.  See joblib.Parallel class. 
       value: 1
      